spring.main.web-environment: false
logging.file: app.log

oanda:
  traders:
    - # TODO: Use a better trading strategy when possible
      account: '101-001-1775714-001'
      strategy: OPEN_RANDOM_POSITION
  api:
    endpoint: 'https://api-fxpractice.oanda.com'
    token: 'inserted from properties'

---
spring:
  profiles: simulation

logging.level.live: warn
logging.level.trader: warn

simulation:
  startTime: 2017-01-01 01:00
  endTime: 2017-12-31 23:59
  millisDelayBetweenMinutes: 0
  pippeteSpread: 20
  instancesPerTraderType: 2
  tradingStrategies: OPEN_RANDOM_POSITION, SMARTER_RANDOM_POSITION



---
spring:
  profiles: prod

oanda:
  endpoint: 'https://api-fxtrade.oanda.com/'

---
spring:
  profiles: demo

oanda:
  traders:
    - # 30/60 SL/TP
      account: '101-001-1775714-002'
      strategy: OPEN_RANDOM_POSITION
    - # 10/10 SL/TP
      account: '101-001-1775714-003'
      strategy: OPEN_RANDOM_POSITION_HIGH_FREQUENCY