spring:
  main:
    web-application-type: none

logging.file: app.log

oanda:
  traders:
  - # TODO: Use a better trading strategy when possible
    account: '101-001-1775714-001'
    strategy: OPEN_RANDOM_POSITION
  api:
    endpoint: 'https://api-fxpractice.oanda.com'
    token: 'inserted from properties'

---
spring: # Simulated backtesting
  profiles: simulation

logging.level.live: warn
logging.level.trader: warn

simulation:
  startTime: 2017-01-01 01:00
  endTime: 2017-12-31 23:59
  millisDelayBetweenMinutes: 0
  accountBalanceDollars: 50
  pippeteSpread: 20
  instancesPerTraderType: 2
  tradingStrategies: SMARTER_MARTINGALE, OPEN_RANDOM_POSITION, SMARTER_RANDOM_POSITION

---
spring: # Integration test
  profiles: integration

logging.level.live: warn
logging.level.trader: warn

simulation:
  startTime: 2017-01-01 01:00
  endTime: 2017-12-31 23:59
  millisDelayBetweenMinutes: 0
  accountBalanceDollars: 50
  pippeteSpread: 20
  instancesPerTraderType: 2
  tradingStrategies: HISTORY_COMPARATOR2, REGRESSION_COMPARATOR

---
spring: # Real trading accounts with live brokers
  profiles: prod

oanda:
  endpoint: 'https://api-fxtrade.oanda.com/'

---
spring: # Demo trading accounts with live brokers
  profiles: demo

oanda:
  traders:
  - # 30/60 SL/TP
    account: '101-001-1775714-002'
    strategy: OPEN_RANDOM_POSITION
  - # 10/10 SL/TP
    account: '101-001-1775714-003'
    strategy: OPEN_RANDOM_POSITION_HIGH_FREQUENCY
  - # 100/200 SL/TP
    account: '101-001-1775714-004'
    strategy: SMARTER_RANDOM_POSITION
  - # 30/60 SL/TP
    account: '101-001-1775714-005'
    strategy: SMARTER_MARTINGALE
  - # 10/20 SL/TP
    account: '101-001-1775714-007'
    strategy: HISTORY_COMPARATOR2
  - # 10/10 SL/TP
    account: '101-001-1775714-008'
    strategy: HIGH_FREQ_MARTINGALE
  - # 10/10 SL/TP
    account: '101-001-1775714-009'
    strategy: HIGH_FREQ_MARTINGALE_FIVEK_START
  - # 10/10 SL/TP
    account: '101-001-1775714-010'
    strategy: HIGH_FREQ_MARTINGALE_FIVEK_START
  - # 10/10 SL/TP
    account: '101-001-1775714-011'
    strategy: HIGH_FREQ_MARTINGALE_FIVEK_START
  - # 10/10 SL/TP
    account: '101-001-1775714-012'
    strategy: HIGH_FREQ_MARTINGALE_FIVEK_START
  - # 10/10 SL/TP
    account: '101-001-1775714-013'
    strategy: HIGH_FREQ_MARTINGALE_FIVEK_START
  - # 10/10 SL/TP
    account: '101-001-1775714-014'
    strategy: HIGH_FREQ_MARTINGALE_FIVEK_START
  - # 10/10 SL/TP
    account: '101-001-1775714-015'
    strategy: HIGH_FREQ_MARTINGALE_FIVEK_START
  - # 10/10 SL/TP
    account: '101-001-1775714-016'
    strategy: HIGH_FREQ_MARTINGALE_FIVEK_START
  - # 10/10 SL/TP
    account: '101-001-1775714-017'
    strategy: HIGH_FREQ_MARTINGALE_FIVEK_START
  - # 10/10 SL/TP
    account: '101-001-1775714-018'
    strategy: HIGH_FREQ_MARTINGALE_FIVEK_START
  - # 10/10 SL/TP
    account: '101-001-1775714-019'
    strategy: HIGH_FREQ_MARTINGALE_FIVEK_START
  - # 10/10 SL/TP
    account: '101-001-1775714-020'
    strategy: HIGH_FREQ_MARTINGALE_FIVEK_START
